---
# Requires Ansible >= 1.9
- hosts: all
  roles:
  #- dumpvars
  - ispmail-packages
  - ispmail-letsencrypt
  - ispmail-database
  - ispmail-postfix
  - ispmail-dovecot
  - ispmail-webmail
  - ispmail-webmail-apache
  - ispmail-passenger
  - ispmail-on-rails
