---
- name: Create a self-signed certificate
  command: >
    openssl req -newkey rsa:4096
      -nodes -sha512 -x509
      -days {{ ispmail_certificate_days_valid }}
      -nodes
      -subj "/C={{ ispmail_certificate_country }}/ST={{ ispmail_certificate_state }}/L={{ ispmail_certificate_location }}/O={{ ispmail_certificate_organisation }}/OU={{ ispmail_certificate_orgunit }}{% for domain in ispmail_certificate_domains %}/CN={{ domain }}{% endfor %}/emailAddress={{ ispmail_certificate_email }}"
      -out /etc/letsencrypt/live/{{ispmail_webmail_hostname}}/fullchain.pem
      -keyout /etc/letsencrypt/live/{{ispmail_webmail_hostname}}/privkey.pem
  args:
    creates: /etc/ssl/certs/mailserver.pem
- name: Restrict access permissions of the private key
  file: path=/etc/letsencrypt/live/{{ispmail_webmail_hostname}}/privkey.pem mode=0640

